#香满园 端口配置
app:
  name: "web_app"
  mode: "dev"
  port: 7777
  version: "v1"

#日志
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 300  #每个人日志文件大小
  max_age: 30    #存储天数
  max_backups: 7 #备份数量

#数据库 配置
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "paymentPlatform"
  password: "JBD7KNBnJaB7E8HY"
  dbname: "paymentplatform"


#redis  配置
redis:
  host: "127.0.0.1"
  port: 6379
  db: 9
  password: "wy011620."
  pool_size: 20


# 系统设置
eth:
  apikey: "5YJ37XCEQFSEDMMI6RXZ756QB7HS2VT921"
  ethUrl: "https://mainnet.infura.io/v3/a73f8de0d9974dd7a35c5d241e24e853"
  https: "1"     #  1 代表htttps 请求  2代表http 请求
  sslPem: "1_wyLoveeat.com_bundle.pem"
  sslKey: "0_wyLoveeat.com.key"
  ThreeUrl: "http://127.0.0.1:7777"
  OrderEffectivityTime: 3600  #秒
  ApiKey: "6e347830f78d54482097d177f7278fb8"   #解密的秘钥
  RechargingJumpAddress: "http://8.136.97.179:7777/static/pay/#/"



